server:
  servlet:
    context-path: /api
    session:
      cookie:
        http-only: false
        path: /

spring:
  application:
    name: testy-savings-be
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: false
        generate-ddl: true
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: create
    database: mysql



  cache:
    type: redis
  data:
    mongodb:
      uri: ${MONGO_URL}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      repositories:
        enabled: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - gender
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

server_host:
  ai: ${AI_HOST}
  front_url: ${FRONT_HOST}
